package models

import "time"

// Message represents a chat message
type Message struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"room_id"`
	AgentID     string    `json:"agent_id"`
	AgentName   string    `json:"agent_name"`
	AgentIndex  int       `json:"agent_index"` // 1-based number shown in UI
	ProviderID  string    `json:"provider_id"`
	Content     string    `json:"content"`
	Timestamp   time.Time `json:"timestamp"`
	TokensUsed  int       `json:"tokens_used,omitempty"`
	IsSystem    bool      `json:"is_system,omitempty"` // system directive injected message
	IsPrivate   bool      `json:"is_private,omitempty"`
	PrivateTo   string    `json:"private_to,omitempty"`
	PrivateFrom string    `json:"private_from,omitempty"`
}

// Agent represents an AI participant in the chatroom
type Agent struct {
	ID          string `json:"id"`
	Index       int    `json:"index"` // assigned number in the room, 1-based
	Name        string `json:"name"`
	ProviderID  string `json:"provider_id"`
	Personality string `json:"personality"` // System prompt for personality
	AvatarColor string `json:"avatar_color"`
	AvatarImage string `json:"avatar_image,omitempty"` // base64 data URL or URL
	PersonaID   string `json:"persona_id,omitempty"`   // linked preset persona
	IsReferee   bool   `json:"is_referee,omitempty"`   // AI referee: generates system commands and judges stop condition
	IsObserver  bool   `json:"is_observer,omitempty"`  // Observer only reacts to system directives
	IsAssistant bool   `json:"is_assistant,omitempty"` // Referee assistant role (still participates in discussion)
	IsRefereeAdded bool `json:"is_referee_added,omitempty"` // Created by referee via [ADD_AI]
}

// Room represents a chat room
type Room struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	Topic         string    `json:"topic"`
	Rules         string    `json:"rules"`
	Agents        []Agent   `json:"agents"`
	Messages      []Message `json:"messages"`
	IsRunning     bool      `json:"is_running"`
	CreatedAt     time.Time `json:"created_at"`
	MaxMessages   int       `json:"max_messages"`              // 0 = unlimited
	SpeakOrder    []int     `json:"speak_order,omitempty"`     // agent indexes in speak order; empty = sequential
	StopCondition string    `json:"stop_condition,omitempty"`  // keyword/phrase; engine stops when any AI message contains it
	ClonedFrom    string    `json:"cloned_from,omitempty"`     // source room ID if cloned
}

// WSEvent represents a WebSocket event
type WSEvent struct {
	Type    string      `json:"type"`
	Payload interface{} `json:"payload"`
}

// WSEventType constants
const (
	EventMessage    = "message"
	EventRoomUpdate = "room_update"
	EventError      = "error"
	EventStatus     = "status"
	EventSysCmd     = "system_cmd"  // system command injected
	EventStopped    = "stop_condition_met" // engine stopped because stop condition matched
)

// SystemCommand is sent from the UI or AI referee to intervene in the current discussion
type SystemCommand struct {
	RoomID      string `json:"room_id"`
	Text        string `json:"text"`              // human-readable directive shown in chat
	FromReferee bool   `json:"from_referee,omitempty"` // true when generated by AI referee
	StopRoom    bool   `json:"stop_room,omitempty"`    // referee signals to stop the room
}

// RoomTemplate is a reusable room configuration preset
type RoomTemplate struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Topic         string   `json:"topic"`
	Rules         string   `json:"rules"`
	StopCondition string   `json:"stop_condition,omitempty"`
	MaxMessages   int      `json:"max_messages"`
	Description   string   `json:"description,omitempty"`
	Tags          []string `json:"tags,omitempty"`
}

// AIPersona is a reusable preset AI role configuration
type AIPersona struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Personality string   `json:"personality"`
	AvatarColor string   `json:"avatar_color"`
	AvatarImage string   `json:"avatar_image,omitempty"` // base64 data URL
	VideoURL    string   `json:"video_url,omitempty"`   // base64 data URL for entrance animation video
	FolderID    string   `json:"folder_id,omitempty"`
	Tags        []string `json:"tags,omitempty"`
	IsReferee   bool     `json:"is_referee,omitempty"` // marks this persona as a referee preset
}

// PersonaFolder is a folder/category for organizing AI personas
type PersonaFolder struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// AIRequest for OpenAI-compatible API
type AIRequest struct {
	Model       string      `json:"model"`
	Messages    []AIMessage `json:"messages"`
	MaxTokens   int         `json:"max_tokens,omitempty"`
	Temperature float64     `json:"temperature,omitempty"`
	Stream      bool        `json:"stream"`
}

type AIMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// AIResponse from OpenAI-compatible API
type AIResponse struct {
	Choices []struct {
		Message      AIMessage `json:"message"`
		FinishReason string    `json:"finish_reason"`
	} `json:"choices"`
	Usage struct {
		TotalTokens int `json:"total_tokens"`
	} `json:"usage"`
	Error *struct {
		Message string `json:"message"`
		Code    string `json:"code"`
	} `json:"error,omitempty"`
}
